# codemagic.yaml
workflows:
  ios-release:
    name: iOS Release (Flutter)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      groups:
        - firebase_ios
      vars:
        BUNDLE_ID: com.miladpirayegarhash.scholar
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID

    integrations:
      app_store_connect: codemagic_app_store_connect

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Write Firebase iOS plist
        script: |
          if [ -z "$FIREBASE_IOS_PLIST_B64" ]; then
            echo "Missing FIREBASE_IOS_PLIST_B64 env var."
            exit 1
          fi
          echo "$FIREBASE_IOS_PLIST_B64" | base64 --decode > ios/Runner/GoogleService-Info.plist
          if grep -q "REPLACE_IN_CI" ios/Runner/GoogleService-Info.plist; then
            echo "GoogleService-Info.plist is placeholder, not real Firebase config."
            exit 1
          fi
          if ! /usr/libexec/PlistBuddy -c "Print:BUNDLE_ID" ios/Runner/GoogleService-Info.plist | grep -qx "$BUNDLE_ID"; then
            echo "Firebase plist BUNDLE_ID does not match $BUNDLE_ID."
            exit 1
          fi

      - name: Set iOS bundle id
        script: |
          sed -i '' 's/com.example.scholarMobile/com.miladpirayegarhash.scholar/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Initialize keychain
        script: keychain initialize

      - name: Add certs to keychain
        script: keychain add-certificates

      - name: Apply provisioning profiles
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter pub get
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
