workflows:
  ios-release:
    name: iOS Release (Flutter)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.miladpirayegarhash.scholar
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID

    integrations:
      app_store_connect: codemagic_app_store_connect

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Build IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
